SVGRendererImpl.exception.UnableToWriteChartImage={0}에서 정의된 SVG 출력 핸들에 차트 이미지를 쓸 수 없습니다.

SVGGraphics2D.drawImage.image=SVG 렌더러 - drawImage(Image arg0, AffineTransform arg1, ImageObserver arg2) - 지원 안 됨

SVGGraphics2D.drawImage.buffer=SVG 렌더러 -drawImage(BufferedImage arg0, BufferedImageOp arg1, int arg2,\tint arg3) - 지원 안됨

SVGGraphics2D.drawRenderImage.RenderImage=SVG 렌더러 -drawRenderedImage(RenderedImage arg0, AffineTransform arg1) - 지원 안 됨

SVGGraphics2D.drawRenderableImage.RenderableImage=SVG 렌더러 - drawRenderableImage(RenderableImage arg0, AffineTransform arg1) - 지원 안 됨

SVGGraphics2D.drawString.StringInt=SVG 렌더러 - drawString(String arg0, int arg1, int arg2) - 지원 안 됨

SVGGraphics2D.drawString.StringFloat=SVG 렌더러 - drawString(String arg0, float arg1, float arg2) - 지원 안 됨

SVGGraphics2D.drawString.AttributeInt=SVG 렌더러 - drawString(AttributedCharacterIterator arg0, int arg1, int arg2) - 지원 안 됨

SVGGraphics2D.drawString.AttributeFloat=SVG 렌더러 - drawString(AttributedCharacterIterator arg0, float arg1, float arg2) - 지원 안 됨

SVGGraphics2D.hit.Rectangle=SVG 렌더러 - hit(Rectangle arg0, Shape arg1, boolean arg2) - 지원 안 됨

SVGGraphics2D.getDeviceConfig=SVG 렌더러 - GraphicsConfiguration getDeviceConfiguration() - 지원 안 됨

SVGGraphics2D.setComposite=SVG 렌더러 - setComposite(Composite arg0) - 지원 안 됨

SVGGraphics2D.getRenderingHint.Key=SVG 렌더러 - getRenderingHint(Key arg0) - 지원 안 됨

SVGGraphics2D.setRenderingHints.Map=SVG 렌더러 - setRenderingHints(Map arg0) - 지원 안 됨

SVGGraphics2D.ddRenderingHints.Map=SVG 렌더러 - ddRenderingHints(Map arg0) - 지원 안 됨

SVGGraphics2D.getRenderingHints=SVG 렌더러 - getRenderingHints() - 지원 안 됨

SVGGraphics2D.transform.AffineTransform=SVG 렌더러 - transform(AffineTransform arg0) - 지원 안 됨

SVGGraphics2D.setTransform.Affine=SVG 렌더러 - setTransform(AffineTransform arg0) - 지원 안 됨

SVGGraphics2D.getTransform=SVG 렌더러 - AffineTransform getTransform() - 지원 안 됨

SVGGraphics2D.getComposite=SVG 렌더러 - Composite getComposite() - 지원 안 됨

SVGGraphics2D.setPaintMode=SVG 렌더러 - setPaintMode() - 지원 안 됨

SVGGraphics2D.setXORModel.Color=SVG 렌더러 - setXORMode(Color arg0) - 지원 안 됨

SVGGraphics2D.getFontMetrics.Font=SVG 렌더러 - FontMetrics getFontMetrics(Font arg0) - 지원 안 됨

SVGGraphics2D.CopyArea.Int=SVG 렌더러 - CcopyArea(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5) - 지원 안 됨

SVGGraphics2D.clearRect.Int=SVG 렌더러 - clearRect(int arg0, int arg1, int arg2, int arg3)  - 지원 안 됨

SVGGraphics2D.drawPolyline.Int=SVG 렌더러 - drawPolyline(int[] arg0, int[] arg1, int arg2) - 지원 안 됨
